const kartlar = [
    {baslik: "Kart 1", foto: 1},
    {baslik: "Kart 2", foto: 2},
    {baslik: "Kart 3", foto: 3},
    {baslik: "Kart 4", foto: 4},
    {baslik: "Kart 5", foto: 5},
    {baslik: "Kart 6", foto: 6},
    {baslik: "Kart 7", foto: 7},
    {baslik: "Kart 8", foto: 8},
    {baslik: "Kart 9", foto: 9},
    {baslik: "Kart 10", foto: 10},
    {baslik: "Kart 11", foto: 11},
    {baslik: "Kart 12", foto: 12},
    {baslik: "Kart 13", foto: 13},
    {baslik: "Kart 14", foto: 14},
    {baslik: "Kart 15", foto: 15},
    {baslik: "Kart 16", foto: 16},
    {baslik: "Kart 17", foto: 17},
    {baslik: "Kart 18", foto: 18},
    {baslik: "Kart 19", foto: 19},
    {baslik: "Kart 20", foto: 20},
    {baslik: "Kart 21", foto: 21},
    {baslik: "Kart 22", foto: 22},
    {baslik: "Kart 23", foto: 23},
    {baslik: "Kart 24", foto: 24},
]

export {kartlar}